packages:
    - apps/*
    - packages/*
onlyBuiltDependencies:
    - "@tailwindcss/oxide"
    - better-sqlite3
    - core-js-pure
    - esbuild
    - msgpackr-extract
    - puppeteer
    - sharp
    - unrs-resolver
