name: API Docker Image CI

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push API image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  image: anycrawl-api
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  multiPlatform: true
                  platform: linux/amd64,linux/arm64
                  dockerfile: ./apps/api/Dockerfile
                  tags: latest,${GITHUB_REF#refs/tags/}
